name = "AlgebraicRelations"
uuid = "1c3ea84b-a956-4dfe-a2f4-485757f48f1d"
authors = ["bosonbaas <bosonbaas@gmail.com>"]
version = "0.1.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
